#!user/bin/env python
#-*-coding:utf-8 -*-
# Author: Sy106
import json

def user_input():
    num=input("please input the number[1:get the info or 2:add the info or 3:delete the info]:[q=quit]:").strip()
    if num=='1':
        read = input('pls input the backend:')
        with open('config_old', 'r', encoding="utf-8") as f1, open("config_new", 'w', encoding="utf-8") as f2:
            for line in f1:
                if line.strip() == 'backend'+' '+read:#如果匹配到输入的内容，就输出标题下的内容
                  list=f1.readlines()
                  index=list.index('\n')#将空行前的内容输出
                  for i in range(index):
                      print(list[i].strip())
        pass
    elif num=='2':
        read = input('pls input the add record:')
        read_dict = json.loads(read)
        print(read_dict)

        pass
    elif num=='3':
        printread = input('pls input the delete record:')
        pass
    elif num=='q'or num=='quit':
        exit("Bye!")
    else:
        print("please input the auth number!")
        exit("Bye!")

while True:
 user_input()
