# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20170218_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type_id',
            field=models.IntegerField(choices=[(0, 'Python'), (1, 'OpenStack'), (2, 'Linux')], default=0),
            preserve_default=False,
        ),
    ]
