# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20161203_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(max_length=36),
        ),
    ]
